Update action versions
julelang/jule pull request #46
Opened 2023-09-10 06:31 UTC by Panquesito7

### Description

- Update action versions.
- Add a test that wasn't being run. 

### Checklist

- [ x A description of the changes in this PR is mentioned above.
- [x] All the new and existing tests pass.
- [x] The code follows the code style and conventions of the project.
- [x] No plagiarized, duplicated, or repetitive code that has been directly copied from another source.
- [x] I have read the whole [Contributing guidelines](https://jule.dev/contribute) of the project and its resources/related pages.

### Note to reviewers

None.

2023-09-10 19:10 UTC, Panquesito7 commented
Looks like the calculator test isn't working properly. 👀
Should I create another issue for that?

2023-09-10 19:11 UTC, mertcandav commented
> Looks like the calculator test isn't working properly. 👀
> Should I create another issue for that?

Yeah, please.

2023-09-10 22:29 UTC, mertcandav commented
> > Looks like the calculator test isn't working properly. 👀
> > Should I create another issue for that?
> 
> Yeah, please.

Oh. After waiting 2h 46m 40s for input, CI failed.
So, I think we don't need to issue for this.
I guess removing execution of basic calculator test is enough.

2023-09-12 21:36 UTC, mertcandav requested changes

2023-09-12 21:36 UTC, mertcandav commented on .github/workflows/tests.yml
> +          ./test
```suggestion
```

Basic calculator test is should be just compile-test without execution.
Because needs data from command-line.

2023-09-12 21:38 UTC, mertcandav approved these changes

2023-09-12 21:39 UTC, merged

2023-10-04 18:15 UTC, Panquesito7 commented on .github/workflows/tests.yml
> +          ./test
Should we add input when running the command, then? Or should we just not test it?